# Generated by Django 4.2.4 on 2023-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('timings', models.DecimalField(decimal_places=2, max_digits=2)),
                ('image', models.ImageField(upload_to='images/ground/')),
            ],
        ),
    ]
