# Generated by Django 4.2.4 on 2023-10-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0002_addground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addground',
            name='timings',
            field=models.TextField(),
        ),
    ]
