# Generated by Django 4.2.4 on 2023-10-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0004_addground_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='type',
            field=models.CharField(default='#', max_length=20),
        ),
        migrations.AlterField(
            model_name='addground',
            name='image',
            field=models.ImageField(upload_to='user'),
        ),
    ]
