# Generated by Django 4.2.4 on 2023-10-07 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0005_usermodel_type_alter_addground_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addground',
            name='price',
            field=models.CharField(default='1000', max_length=5),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.CharField(default='3 PM', max_length=10)),
                ('hours', models.CharField(default='1', max_length=2)),
                ('ground_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nisapp.addground')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
