# Generated by Django 4.2.4 on 2023-10-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0006_addground_price_alter_usermodel_type_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sports',
            field=models.CharField(default='cricket', max_length=30),
        ),
    ]
