# Generated by Django 4.2.4 on 2023-10-07 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0007_booking_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addground',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
