# Generated by Django 4.2.6 on 2023-10-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisapp', '0009_tournament_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('city_town', models.CharField(max_length=100)),
                ('captain_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('captain_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
